import { useNavigate } from 'react-router-dom';
import { useHealth, useSyllabus } from '@/hooks';
import { Button, Card, Loader } from '@/components/common';
import { BookOpen, Brain, Target, Zap } from 'lucide-react';

export default function HomePage() {
  const navigate = useNavigate();
  const { data: health, isLoading: healthLoading } = useHealth();
  const { data: syllabus, isLoading: syllabusLoading } = useSyllabus();

  if (healthLoading || syllabusLoading) {
    return <Loader message="Loading dashboard..." />;
  }

  const stats = [
    {
      icon: BookOpen,
      label: 'Topics',
      value: syllabus?.length || 0,
      color: 'text-blue-500',
      bgColor: 'bg-blue-50 dark:bg-blue-900/20',
    },
    {
      icon: Brain,
      label: 'AI Model',
      value: health?.llm_model?.split(':')[0] || 'N/A',
      color: 'text-purple-500',
      bgColor: 'bg-purple-50 dark:bg-purple-900/20',
    },
    {
      icon: Target,
      label: 'Database',
      value: health?.database || 'Connected',
      color: 'text-green-500',
      bgColor: 'bg-green-50 dark:bg-green-900/20',
    },
    {
      icon: Zap,
      label: 'Status',
      value: health?.status || 'OK',
      color: 'text-yellow-500',
      bgColor: 'bg-yellow-50 dark:bg-yellow-900/20',
    },
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-primary/10 via-transparent to-purple-500/10 dark:from-primary/5 dark:to-purple-500/5">
      {/* Hero Section */}
      <div className="text-center py-16 px-6">
        <h1 className="text-5xl md:text-6xl font-bold mb-4 bg-clip-text text-transparent bg-gradient-to-r from-primary to-purple-600">
          Welcome to StudyAI
        </h1>
        <p className="text-xl text-slate-600 dark:text-slate-300 max-w-2xl mx-auto mb-8">
          Learn smarter with AI-powered lessons and personalized quizzes
        </p>
        <Button
          size="lg"
          onClick={() => navigate('/syllabus')}
          className="inline-block"
        >
          <BookOpen size={20} />
          Start Learning
        </Button>
      </div>

      {/* Stats Section */}
      <div className="max-w-6xl mx-auto px-6 py-12">
        <h2 className="text-2xl font-bold mb-8 text-slate-900 dark:text-white">
          System Status
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          {stats.map(({ icon: Icon, label, value, color, bgColor }) => (
            <Card key={label} className={`${bgColor}`}>
              <div className="flex items-start gap-4">
                <div className={`p-3 rounded-lg ${color} bg-white dark:bg-slate-700`}>
                  <Icon size={24} />
                </div>
                <div>
                  <p className="text-sm text-slate-600 dark:text-slate-400 font-medium">
                    {label}
                  </p>
                  <p className="text-2xl font-bold text-slate-900 dark:text-white">
                    {value}
                  </p>
                </div>
              </div>
            </Card>
          ))}
        </div>
      </div>

      {/* Features Section */}
      <div className="max-w-6xl mx-auto px-6 py-16">
        <h2 className="text-2xl font-bold mb-8 text-slate-900 dark:text-white">
          Features
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {[
            {
              title: 'AI-Generated Lessons',
              description:
                'Get personalized lessons generated by advanced AI models tailored to your learning level',
              icon: Brain,
            },
            {
              title: 'Interactive Quizzes',
              description:
                'Test your knowledge with AI-powered quizzes that adapt to your progress',
              icon: Target,
            },
            {
              title: 'Comprehensive Curriculum',
              description:
                'Access structured learning paths covering multiple subjects and topics',
              icon: BookOpen,
            },
          ].map(({ title, description, icon: Icon }) => (
            <Card key={title} hoverable>
              <Icon className="text-primary-500 mb-4" size={32} />
              <h3 className="text-lg font-bold mb-2 text-slate-900 dark:text-white">
                {title}
              </h3>
              <p className="text-slate-600 dark:text-slate-400">{description}</p>
            </Card>
          ))}
        </div>
      </div>

      {/* CTA Section */}
      <div className="bg-gradient-to-r from-primary to-purple-600 text-white">
        <div className="max-w-4xl mx-auto px-6 py-16 text-center">
          <h2 className="text-3xl font-bold mb-4">Ready to Learn?</h2>
          <p className="text-lg mb-8 opacity-90">
            Explore thousands of topics and start your learning journey today
          </p>
          <Button
            variant="outline"
            size="lg"
            onClick={() => navigate('/syllabus')}
            className="border-white text-white hover:bg-white/10"
          >
            Browse Curriculum
          </Button>
        </div>
      </div>
    </div>
  );
}
